# Generated by Django 5.0.6 on 2024-08-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='surname',
        ),
    ]
