# Generated by Django 5.0.6 on 2024-08-29 13:02

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_remove_enrollment_name_remove_enrollment_surname'),
        ('invoices', '0013_invoice_student'),
        ('providers', '0065_rename_price_courseprice_week_price_promotional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='date_start',
            new_name='course_date_start',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course_weekly_price',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='enrollment_fee',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='program',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='total',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='accommodation_date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='city', chained_model_field='address__city', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.school'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='accommodation',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='school', chained_model_field='school', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.schoolaccommodation'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='accommodation_qty_weeks',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='accommodation_price_list', chained_model_field='accommodation_price_list', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.accommodationprice'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='airport_transfer',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='school', chained_model_field='school', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.schoolairporttransfer'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='school', chained_model_field='school', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course_qty_weeks',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='course_price_list', chained_model_field='course_price_list', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.courseprice'),
        ),
    ]
