# Generated by Django 5.0.6 on 2024-08-18 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_remove_enrollment_name_remove_enrollment_surname'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='quotations.quotation'),
        ),
    ]
