# Generated by Django 5.0.6 on 2024-08-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_rename_date_start_enrollment_course_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
