# Generated by Django 5.0.6 on 2024-08-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_enrollment_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='quotation',
        ),
    ]
