# Generated by Django 5.0.6 on 2024-08-29 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_enrollment_city'),
        ('invoices', '0013_invoice_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice'),
        ),
    ]
