# Generated by Django 5.0.6 on 2024-08-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_remove_enrollment_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='quotation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
