# Generated by Django 5.0.6 on 2024-08-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_alter_enrollment_city_alter_enrollment_invoice'),
        ('invoices', '0013_invoice_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice'),
        ),
    ]
