# Generated by Django 5.0.6 on 2024-08-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0008_rename_city_enrollment_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='accommodation_date_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_date_finish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
