# Generated by Django 5.0.6 on 2024-08-01 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_delete_sentemail'),
        ('providers', '0044_alter_accommodation_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.school'),
        ),
    ]
