# Generated by Django 5.0.6 on 2024-07-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencybranch',
            old_name='city_id',
            new_name='city',
        ),
    ]
