# Generated by Django 5.0.6 on 2024-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_rename_city_id_agencybranch_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencybranch',
            name='telephone',
            field=models.CharField(max_length=255),
        ),
    ]
