# Generated by Django 5.0.6 on 2024-07-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_agencybranch_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencybranch',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
