# Generated by Django 5.0.6 on 2024-08-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_dob_studentprofile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
    ]
