# Generated by Django 5.0.6 on 2024-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='enrollment_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
