# Generated by Django 5.0.6 on 2024-08-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_enrollment_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='enrollment_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
