# Generated by Django 5.0.6 on 2024-08-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_accommodation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
