# Generated by Django 5.0.6 on 2024-08-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_date_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date_start',
            new_name='accommodation_date_start',
        ),
        migrations.AddField(
            model_name='invoice',
            name='course_date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
