# Generated by Django 5.0.6 on 2024-08-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_invoice_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='accommodation',
            field=models.CharField(max_length=100),
        ),
    ]
