# Generated by Django 5.0.6 on 2024-08-28 21:25

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_invoice_accommodation'),
        ('providers', '0065_rename_price_courseprice_week_price_promotional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='accommodation',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='school', chained_model_field='school', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.schoolaccommodation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='accommodation_qty_weeks',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='accommodation_price_list', chained_model_field='accommodation_price_list', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.accommodationprice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='course',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='school', chained_model_field='school', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.course'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='course_qty_weeks',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='course_price_list', chained_model_field='course_price_list', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.courseprice'),
        ),
    ]
