# Generated by Django 5.0.6 on 2024-08-30 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_alter_invoice_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
