# Generated by Django 5.0.6 on 2024-08-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='accommodation_date_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='course_date_finish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
