# Generated by Django 5.0.6 on 2024-09-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_alter_invoice_city'),
        ('invoices', '0016_invoice_accommodation_date_finish_and_more'),
    ]

    operations = [
    ]
