# Generated by Django 5.0.6 on 2024-07-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='schools/facilities'),
        ),
    ]
