# Generated by Django 5.0.6 on 2024-07-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_activity_schoolactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
