# Generated by Django 5.0.6 on 2024-07-06 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('providers', '0007_accommodation_schoolaccommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTransferAiport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_one_way', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_both_ways', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aiport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.airport')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.school')),
            ],
        ),
    ]
