# Generated by Django 5.0.6 on 2024-07-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_airport_schooltransferaiport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolTransferAiport',
            new_name='SchoolAirportTransfer',
        ),
    ]
