# Generated by Django 5.0.6 on 2024-07-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_rename_schooltransferaiport_schoolairporttransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='airport_transfer',
            field=models.ManyToManyField(through='providers.SchoolAirportTransfer', to='providers.airport'),
        ),
    ]
