# Generated by Django 5.0.6 on 2024-07-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_school_airport_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolairporttransfer',
            old_name='aiport_id',
            new_name='airport_id',
        ),
    ]
