# Generated by Django 5.0.6 on 2024-07-06 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_rename_aiport_id_schoolairporttransfer_airport_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls_week_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hs_week_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('extra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.accommodation')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.school')),
            ],
        ),
    ]
