# Generated by Django 5.0.6 on 2024-07-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0012_extra_schoolextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolextra',
            name='extra_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.extra'),
        ),
    ]
