# Generated by Django 5.0.6 on 2024-07-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0014_avgages_schoolavgages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvgAges',
            new_name='AvgAge',
        ),
        migrations.RenameModel(
            old_name='SchoolAvgAges',
            new_name='SchoolAvgAge',
        ),
        migrations.RenameField(
            model_name='schoolavgage',
            old_name='avg_ages_id',
            new_name='avg_age_id',
        ),
    ]
