# Generated by Django 5.0.6 on 2024-07-09 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0017_rename_nationality_mix_nationalitymix_school_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationalitymix',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='nationalitymix',
            old_name='school_id',
            new_name='school',
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.IntegerField()),
                ('info_email', models.EmailField(max_length=255)),
                ('bookings_email', models.EmailField(max_length=255)),
                ('academics_email', models.EmailField(max_length=255)),
                ('website', models.CharField(max_length=254)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='providers.school')),
            ],
        ),
        migrations.DeleteModel(
            name='SchoolContactInformation',
        ),
    ]
