# Generated by Django 5.0.6 on 2024-07-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0018_rename_country_id_nationalitymix_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='academics_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='bookings_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='website',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
