# Generated by Django 5.0.6 on 2024-07-19 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_rename_city_id_agencybranch_city'),
        ('providers', '0019_alter_contactinformation_academics_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_accommodation',
            field=models.ManyToManyField(through='providers.SchoolAccommodation', to='providers.accommodation'),
        ),
    ]
