# Generated by Django 5.0.6 on 2024-07-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_rename_city_id_agencybranch_city'),
        ('providers', '0020_remove_schoolaccommodation_name_accommodation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='name',
        ),
        migrations.AlterField(
            model_name='schoolaccommodation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
