# Generated by Django 5.0.6 on 2024-07-19 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('branches', '0002_rename_city_id_agencybranch_city'),
        ('providers', '0021_remove_accommodation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
