# Generated by Django 5.0.6 on 2024-07-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_rename_city_id_agencybranch_city'),
        ('providers', '0022_alter_contactinformation_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
