# Generated by Django 5.0.6 on 2024-07-19 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_agencybranch_telephone'),
        ('providers', '0023_alter_contactinformation_telephone_and_more'),
    ]

    operations = [
    ]
