# Generated by Django 5.0.6 on 2024-07-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0025_schoolagencybranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
