# Generated by Django 5.0.6 on 2024-07-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0026_alter_contactinformation_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hours_per_week', models.IntegerField(blank=True, null=True)),
                ('lesson_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('course_material', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('max_students', models.IntegerField(blank=True, null=True)),
                ('student_min_age', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('time_table', models.TextField()),
                ('ls_week_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hs_week_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.school')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='courses',
            field=models.ManyToManyField(through='providers.SchoolCourse', to='providers.course'),
        ),
    ]
