# Generated by Django 5.0.6 on 2024-07-29 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0028_remove_school_courses_delete_schoolcourse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.school'),
        ),
    ]
