# Generated by Django 5.0.6 on 2024-07-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0031_remove_school_address_address_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='providers/schools/'),
        ),
    ]
