# Generated by Django 5.0.6 on 2024-07-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0033_rename_accommodation_id_schoolaccommodation_accommodation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolairporttransfer',
            old_name='airport_id',
            new_name='airport',
        ),
        migrations.RenameField(
            model_name='schoolairporttransfer',
            old_name='school_id',
            new_name='school',
        ),
    ]
