# Generated by Django 5.0.6 on 2024-07-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0035_school_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolextra',
            old_name='extra_id',
            new_name='extra',
        ),
        migrations.RenameField(
            model_name='schoolextra',
            old_name='school_id',
            new_name='school',
        ),
    ]
