# Generated by Django 5.0.6 on 2024-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0036_rename_extra_id_schoolextra_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='avg_age',
            field=models.ManyToManyField(blank=True, null=True, through='providers.SchoolAvgAge', to='providers.avgage'),
        ),
    ]
