# Generated by Django 5.0.6 on 2024-07-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0037_school_avg_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='avg_age',
            field=models.ManyToManyField(blank=True, through='providers.SchoolAvgAge', to='providers.avgage'),
        ),
        migrations.AlterField(
            model_name='school',
            name='extra',
            field=models.ManyToManyField(blank=True, through='providers.SchoolExtra', to='providers.extra'),
        ),
    ]
