# Generated by Django 5.0.6 on 2024-07-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0038_alter_school_avg_age_alter_school_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='avg_age',
            new_name='avg_ages',
        ),
        migrations.RenameField(
            model_name='schoolavgage',
            old_name='avg_age_id',
            new_name='avg_age',
        ),
        migrations.RenameField(
            model_name='schoolavgage',
            old_name='school_id',
            new_name='school',
        ),
    ]
