# Generated by Django 5.0.6 on 2024-07-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0039_rename_avg_age_school_avg_ages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolclassroomequipment',
            old_name='classroom_equipment_id',
            new_name='classroom_equipment',
        ),
        migrations.RenameField(
            model_name='schoolclassroomequipment',
            old_name='school_id',
            new_name='school',
        ),
    ]
