# Generated by Django 5.0.6 on 2024-07-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0040_rename_classroom_equipment_id_schoolclassroomequipment_classroom_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short_description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
