# Generated by Django 5.0.6 on 2024-07-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0042_alter_acreditation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acreditation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='providers/acreditations/'),
        ),
    ]
