# Generated by Django 5.0.6 on 2024-08-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0043_alter_acreditation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='providers/accommodation/'),
        ),
    ]
