# Generated by Django 5.0.6 on 2024-08-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0044_alter_accommodation_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
