# Generated by Django 5.0.6 on 2024-08-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0046_courseprice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseprice',
            unique_together=set(),
        ),
    ]
