# Generated by Django 5.0.6 on 2024-08-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0047_alter_courseprice_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_weeks', models.IntegerField()),
                ('week_price_ls', models.DecimalField(decimal_places=2, max_digits=6)),
                ('week_price_hs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('week_price_promotional', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolaccommodation',
            name='hs_week_price',
        ),
        migrations.RemoveField(
            model_name='schoolaccommodation',
            name='ls_week_price',
        ),
        migrations.CreateModel(
            name='AccommodationPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('prices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.accommodationprice')),
            ],
        ),
    ]
