# Generated by Django 5.0.6 on 2024-08-03 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0049_schoolaccommodation_price_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolaccommodation',
            name='price_list',
        ),
        migrations.AddField(
            model_name='accommodationpricelist',
            name='school_accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.schoolaccommodation'),
        ),
    ]
