# Generated by Django 5.0.6 on 2024-08-03 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0050_remove_schoolaccommodation_price_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationpricelist',
            name='prices',
        ),
        migrations.AddField(
            model_name='accommodationprice',
            name='accommodation_price_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.accommodationpricelist'),
        ),
    ]
