# Generated by Django 5.0.6 on 2024-08-03 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0051_remove_accommodationpricelist_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationprice',
            name='accommodation_price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.accommodationpricelist'),
        ),
    ]
