# Generated by Django 5.0.6 on 2024-08-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0052_alter_accommodationprice_accommodation_price_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolairporttransfer',
            old_name='price_both_ways',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='schoolairporttransfer',
            name='price_one_way',
        ),
    ]
