# Generated by Django 5.0.6 on 2024-08-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0053_rename_price_both_ways_schoolairporttransfer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolairporttransfer',
            name='trip',
            field=models.CharField(blank=True, choices=[('ida', 'ida'), ('ida/vuelta', 'ida/vuelta')], max_length=12, null=True),
        ),
    ]
