# Generated by Django 5.0.6 on 2024-08-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0054_schoolairporttransfer_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolairporttransfer',
            name='trip',
            field=models.CharField(blank=True, choices=[('', 'ida'), ('ida/vuelta', 'ida/vuelta')], max_length=12, null=True),
        ),
    ]
