# Generated by Django 5.0.6 on 2024-08-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0055_alter_schoolairporttransfer_trip'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseprice',
            unique_together={('course', 'weeks')},
        ),
    ]
