# Generated by Django 5.0.6 on 2024-08-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0056_alter_courseprice_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accommodationprice',
            unique_together={('accommodation_price_list', 'qty_weeks')},
        ),
    ]
