# Generated by Django 5.0.6 on 2024-08-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0057_alter_accommodationprice_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='hs_week_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ls_week_price',
        ),
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
