# Generated by Django 5.0.6 on 2024-08-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0058_remove_course_hs_week_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
