# Generated by Django 5.0.6 on 2024-08-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0059_course_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_day',
            field=models.CharField(blank=True, choices=[('lunes', 'lunes'), ('martes', 'martes'), ('miercoles', 'miercoles'), ('jueves', 'jueves'), ('viernes', 'viernes'), ('sabado', 'sabado'), ('domingo', 'domingo')], max_length=20, null=True),
        ),
    ]
