# Generated by Django 5.0.6 on 2024-08-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0060_alter_course_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_day',
            field=models.CharField(blank=True, choices=[('lunes', 'Monday'), ('martes', 'Tuesday'), ('miercoles', 'Wednesday'), ('jueves', 'Thursday'), ('viernes', 'Friday'), ('sabado', 'Saturday'), ('domingo', 'Sunday')], max_length=20, null=True),
        ),
    ]
