# Generated by Django 5.0.6 on 2024-08-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0062_alter_course_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_day',
            field=models.CharField(blank=True, choices=[('monday', 'monday'), ('martes', 'tuesday'), ('miercoles', 'wednesday'), ('jueves', 'thursday'), ('viernes', 'friday'), ('sabado', 'saturday'), ('domingo', 'sunday')], default='monday', max_length=20, null=True),
        ),
    ]
