# Generated by Django 5.0.6 on 2024-08-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0064_school_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseprice',
            old_name='price',
            new_name='week_price_promotional',
        ),
        migrations.AddField(
            model_name='courseprice',
            name='qty_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='week_price_hs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='week_price_ls',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='CoursePriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.course')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='courseprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='course_price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.coursepricelist'),
        ),
        migrations.AlterUniqueTogether(
            name='courseprice',
            unique_together={('course_price_list', 'qty_weeks')},
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='weeks',
        ),
    ]
