# Generated by Django 5.0.6 on 2024-06-27 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0009_alter_message_eml'),
        ('email_client', '0003_custommessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('messageattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_mailbox.messageattachment')),
            ],
            bases=('django_mailbox.messageattachment',),
        ),
        migrations.RenameModel(
            old_name='CustomMessage',
            new_name='Message',
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_mailbox.mailbox',),
        ),
    ]
