# Generated by Django 5.0.6 on 2024-06-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0009_alter_message_eml'),
        ('email_client', '0004_messageattachment_rename_custommessage_message_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ProxyMessage',
        ),
    ]
