# Generated by Django 5.0.6 on 2024-06-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_client', '0005_rename_message_proxymessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='messageattachment_ptr',
        ),
        migrations.RemoveField(
            model_name='proxymessage',
            name='message_ptr',
        ),
        migrations.DeleteModel(
            name='Mailbox',
        ),
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
        migrations.DeleteModel(
            name='ProxyMessage',
        ),
    ]
