# Generated by Django 5.0.6 on 2024-06-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_client', '0006_message_delete_proxymessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='messageattachment_ptr',
        ),
        migrations.DeleteModel(
            name='Mailbox',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
    ]
