# Generated by Django 5.0.6 on 2024-06-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_client', '0007_remove_messageattachment_messageattachment_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
