# Generated by Django 5.0.6 on 2024-06-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_rename_experience_name_experience_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='id',
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
