# Generated by Django 5.0.6 on 2024-08-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_employeeprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencybranch',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agencybranch',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agencybranch',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
