from django.db import models
from django.contrib.auth.models import User

from locations.models import City


class AgencyBranch(models.Model):
    # id autogenerated by django
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    postal_code = models.CharField(max_length=20, null=True, blank=True)
    street_address = models.CharField(max_length=255, null=True, blank=True)
    apartment_number = models.CharField(max_length=20, blank=True, null=True)
    telephone = models.IntegerField()
    info_email = models.EmailField(max_length=255)
    web_link = models.CharField(max_length=255)

    def __str__(self):
        return self.city.name


class EmployeeProfile(models.Model):
    """
    Still need to create a many to many relationship with AgencyBranch.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.CharField(max_length=100)
    job_title = models.CharField(max_length=100)
    branch = models.ForeignKey(AgencyBranch, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} ({self.job_title})"
