from django.db import models
from django.contrib.auth.models import User

from locations.models import City


class AgencyBranch(models.Model):
    # id autogenerated by django
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    telephone = models.IntegerField()
    info_email = models.EmailField(max_length=255)
    web_link = models.CharField(max_length=255)

    def __str__(self):
        return self.city.name


class EmployeeProfile(models.Model):
    """
    Still need to create a many to many relationship with AgencyBranch.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.CharField(max_length=100)
    job_title = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.user.username} - {self.job_title}"