# Generated by Django 5.0.6 on 2024-06-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_sentemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentEmail',
        ),
    ]
