# Generated by Django 5.0.6 on 2024-08-01 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_enquiry'),
        ('providers', '0044_alter_accommodation_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.course'),
        ),
    ]
