# Generated by Django 5.0.6 on 2024-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_enquiry_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='qty_weeks',
            field=models.IntegerField(null=True),
        ),
    ]
