# Generated by Django 5.0.6 on 2024-08-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_enquiry_qty_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
