# Generated by Django 5.0.6 on 2024-08-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0007_enquiry_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enrollment_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
