# Generated by Django 5.0.6 on 2024-08-01 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0009_remove_enquiry_enrollment_fee'),
        ('providers', '0045_course_enrollment_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.schoolaccommodation'),
        ),
    ]
