# Generated by Django 5.0.6 on 2024-08-01 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0013_alter_enquiry_nationality'),
        ('locations', '0001_initial'),
        ('providers', '0045_course_enrollment_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='airport_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.schoolairporttransfer'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country'),
        ),
    ]
