# Generated by Django 5.0.6 on 2024-08-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0014_enquiry_airport_transfer_alter_enquiry_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enrollment_fee',
            field=models.IntegerField(default=1),
        ),
    ]
