# Generated by Django 5.0.6 on 2024-08-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0015_enquiry_enrollment_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='course_weekly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
