# Generated by Django 5.0.6 on 2024-08-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0016_enquiry_course_weekly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
