# Generated by Django 5.0.6 on 2024-08-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0017_enquiry_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
