# Generated by Django 5.0.6 on 2024-08-02 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0018_alter_enquiry_total'),
        ('providers', '0046_courseprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='qty_weeks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.courseprice'),
        ),
    ]
