# Generated by Django 5.0.6 on 2024-08-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_agencybranch_telephone'),
        ('enquiries', '0024_enquiry_accommodation_qty_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.agencybranch'),
        ),
    ]
