# Generated by Django 5.0.6 on 2024-08-13 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_employeeprofile'),
        ('enquiries', '0025_enquiry_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.employeeprofile'),
        ),
    ]
