# Generated by Django 5.0.6 on 2024-08-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0026_enquiry_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='rating',
            field=models.CharField(blank=True, choices=[('hot', 'hot'), ('cold', 'cold'), ('enrolled', 'enrolled')], max_length=10, null=True),
        ),
    ]
