# Generated by Django 5.0.6 on 2024-08-14 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0027_enquiry_follow_up_date_enquiry_rating'),
        ('students', '0004_studentprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
    ]
