# Generated by Django 5.0.6 on 2024-08-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=50)),
                ('content_title', models.CharField(blank=True, max_length=50, null=True)),
                ('header_sub_title', models.CharField(blank=True, max_length=150, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
