# Generated by Django 5.0.6 on 2024-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='content_sub_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
