# Generated by Django 5.0.6 on 2024-08-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='content_sub_title',
            new_name='content_subtitle',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='header_sub_title',
            new_name='header_subtitle',
        ),
    ]
