# Generated by Django 5.0.6 on 2024-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_content_sub_title_aboutus_content_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(upload_to='home/about_us/'),
        ),
    ]
