# Generated by Django 5.0.6 on 2024-08-16 18:40

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_teammember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
