# Generated by Django 5.0.6 on 2024-08-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_aboutus_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to='home/about_us/header'),
        ),
    ]
