# Generated by Django 5.0.6 on 2024-08-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_aboutus_header_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=50)),
                ('header_subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('header_img', models.ImageField(blank=True, null=True, upload_to='home/contact/header')),
                ('form_tag', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
