# Generated by Django 5.0.6 on 2024-08-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=50)),
                ('header_subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('header_img_main', models.ImageField(blank=True, null=True, upload_to='home/home/header')),
                ('header_img_first', models.ImageField(blank=True, null=True, upload_to='home/home/header')),
                ('header_img_second', models.ImageField(blank=True, null=True, upload_to='home/home/header')),
                ('header_img_third', models.ImageField(blank=True, null=True, upload_to='home/home/header')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='home/home/reviews')),
                ('review', models.TextField()),
            ],
        ),
    ]
