# Generated by Django 5.0.6 on 2024-08-19 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_section_studentreview_delete_reviewssection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreview',
            name='review_section',
        ),
        migrations.AddField(
            model_name='studentreview',
            name='home_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepage'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='section_title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
