# Generated by Django 5.0.6 on 2024-08-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_studentreview_review_section_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentReview',
            new_name='StudentReviewsSection',
        ),
    ]
