# Generated by Django 5.0.6 on 2024-08-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_whyussection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whyussection',
            name='age',
        ),
        migrations.RemoveField(
            model_name='whyussection',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='whyussection',
            name='last_name',
        ),
        migrations.AddField(
            model_name='whyussection',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whyussection',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
