# Generated by Django 5.0.6 on 2024-08-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_whyussection_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyussection',
            name='icon_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
