# Generated by Django 5.0.6 on 2024-08-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_whyussection_icon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyussection',
            name='text',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
