# Generated by Django 5.0.6 on 2024-08-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_whyussection_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyussection',
            name='icon_img',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='whyussection',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
