# Generated by Django 5.0.6 on 2024-08-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_whyussection_icon_img_alter_whyussection_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreviewssection',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentreviewssection',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
