# Generated by Django 5.0.6 on 2024-08-19 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_studentreviewssection_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_title', models.TextField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=50, null=True)),
                ('button_first_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_sencond_text', models.CharField(blank=True, max_length=50, null=True)),
                ('home_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepage')),
            ],
        ),
    ]
