# Generated by Django 5.0.6 on 2024-08-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_contactsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsection',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='home/home/contact'),
        ),
    ]
