# Generated by Django 5.0.6 on 2024-08-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_contactsection_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsection',
            old_name='button_sencond_text',
            new_name='button_second_text',
        ),
    ]
