# Generated by Django 5.0.6 on 2024-08-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_button_sencond_text_contactsection_button_second_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=150, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='home/home/featured_programs')),
            ],
        ),
    ]
