# Generated by Django 5.0.6 on 2024-08-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_featuredprograms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturedPrograms',
            new_name='FeaturedProgramsSection',
        ),
    ]
