# Generated by Django 5.0.6 on 2024-08-19 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_featuredprograms_featuredprogramssection'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredprogramssection',
            name='home_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepage'),
        ),
    ]
