# Generated by Django 5.0.6 on 2024-08-19 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_featuredprogramssection_home_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDestiniesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=150, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='home/home/featured_programs')),
                ('home_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepage')),
            ],
        ),
    ]
