# Generated by Django 5.0.6 on 2024-08-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_populardestiniessection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populardestiniessection',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='home/home/popular_destinies'),
        ),
    ]
