# Generated by Django 5.0.6 on 2024-08-20 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_agencybranch_apartment_number_and_more'),
        ('home', '0031_alter_navbaritem_order_alter_navbaritem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.agencybranch'),
        ),
    ]
