# Generated by Django 5.0.6 on 2024-08-29 09:49

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_aboutus_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
