# Generated by Django 5.0.6 on 2024-08-27 13:23

import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0065_rename_price_courseprice_week_price_promotional_and_more'),
        ('quotations', '0023_alter_quotation_accommodation_price_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='accommodation',
        ),
        migrations.AddField(
            model_name='quotation',
            name='accommodation',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='school', chained_model_field='school', null=True, to='providers.schoolaccommodation'),
        ),
    ]
