# Generated by Django 5.0.6 on 2024-08-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0035_alter_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'approved'), ('PENDING', 'pending'), ('INACTIVE', 'inactive'), ('REJECTED', 'rejected')], max_length=255, null=True, verbose_name='status'),
        ),
    ]
