# Generated by Django 5.0.6 on 2024-08-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0039_alter_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='accommodation_date_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='course_date_finish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
