# Generated by Django 5.0.6 on 2024-06-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0009_alter_message_eml'),
        ('email_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMailbox',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_mailbox.mailbox',),
        ),
    ]
