# Generated by Django 5.0.6 on 2024-06-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0009_alter_message_eml'),
        ('email_client', '0002_custommailbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomMailbox',
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_mailbox.mailbox',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_mailbox.message',),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_mailbox.messageattachment',),
        ),
    ]
