# Generated by Django 5.0.6 on 2024-06-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_client', '0003_delete_custommailbox_mailbox_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'verbose_name': 'Message Attachment', 'verbose_name_plural': 'Messages Attachements'},
        ),
    ]
