# Generated by Django 5.0.6 on 2024-06-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_client', '0004_alter_messageattachment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Inbox', 'verbose_name_plural': 'Inbox'},
        ),
    ]
