# Generated by Django 5.0.6 on 2024-06-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_client', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'verbose_name': 'Email Attachment', 'verbose_name_plural': 'Email Attachments'},
        ),
        migrations.AlterModelOptions(
            name='sentemail',
            options={'verbose_name': 'Sent', 'verbose_name_plural': 'Sent'},
        ),
    ]
