# Generated by Django 5.0.6 on 2024-06-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_client', '0007_alter_messageattachment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('recipient', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sent',
                'verbose_name_plural': 'Sent',
            },
        ),
    ]
