# Generated by Django 5.0.6 on 2024-07-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_client', '0008_composeemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composeemail',
            options={'verbose_name': 'Compose', 'verbose_name_plural': 'Compose'},
        ),
    ]
