# Generated by Django 5.0.6 on 2024-06-25 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('course_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('include_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='NotInclude',
            fields=[
                ('not_include_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience_name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('allows_work', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('city', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='experiences/')),
                ('duration_from_weeks', models.IntegerField()),
                ('duration_to_weeks', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school_name', models.CharField(max_length=255)),
                ('school_course_name', models.CharField(max_length=255)),
                ('school_course_description', models.TextField()),
                ('course_weeks_duration', models.IntegerField()),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('school_course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.coursetype')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.experience')),
                ('include', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.include')),
            ],
            options={
                'unique_together': {('experience', 'include')},
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='includes',
            field=models.ManyToManyField(related_name='included_in_experiences', through='programs.ExperienceIncluded', to='programs.include'),
        ),
        migrations.CreateModel(
            name='ExperienceNotIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.experience')),
                ('not_include', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.notinclude')),
            ],
            options={
                'unique_together': {('experience', 'not_include')},
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='not_includes',
            field=models.ManyToManyField(related_name='not_included_in_experiences', through='programs.ExperienceNotIncluded', to='programs.notinclude'),
        ),
        migrations.CreateModel(
            name='ExperienceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.experience')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.requirement')),
            ],
            options={
                'unique_together': {('experience', 'requirement')},
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='requirements',
            field=models.ManyToManyField(related_name='required_in_experiences', through='programs.ExperienceRequirement', to='programs.requirement'),
        ),
    ]
