# Generated by Django 5.0.6 on 2024-06-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_coursetype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
    ]
