# Generated by Django 5.0.6 on 2024-06-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_experience_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='include',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notinclude',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
