# Generated by Django 5.0.6 on 2024-06-25 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('programs', '0004_alter_include_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city'),
        ),
    ]
