# Generated by Django 5.0.6 on 2024-06-25 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('programs', '0005_alter_experience_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.country'),
            preserve_default=False,
        ),
    ]
