# Generated by Django 5.0.6 on 2024-06-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_experience_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='country',
        ),
    ]
