# Generated by Django 5.0.6 on 2024-06-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_remove_experience_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='img',
            field=models.ImageField(upload_to='programs/media'),
        ),
    ]
