# Generated by Django 5.0.6 on 2024-06-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_alter_include_icon_alter_notinclude_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
