# Generated by Django 5.0.6 on 2024-06-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_alter_experience_max_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='experience_name',
            new_name='name',
        ),
    ]
