# Generated by Django 5.0.6 on 2024-06-25 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_alter_experience_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='school_course_description',
            new_name='course_description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='school_course_name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='school_course_type',
            new_name='course_type',
        ),
    ]
