# Generated by Django 5.0.6 on 2024-06-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_rename_school_course_description_experience_course_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetype',
            old_name='course_type_id',
            new_name='id',
        ),
    ]
