# Generated by Django 5.0.6 on 2024-08-15 10:28

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_remove_experience_course_description_and_more'),
        ('providers', '0065_rename_price_courseprice_week_price_promotional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='course',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='school', chained_model_field='school', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.course'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.school'),
        ),
    ]
