# Generated by Django 5.0.6 on 2024-08-15 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_experience_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.experiencefaq'),
        ),
    ]
