# Generated by Django 5.0.6 on 2024-08-15 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_experiencefaq_experience_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='faq',
        ),
        migrations.AddField(
            model_name='experiencefaq',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.experience'),
        ),
    ]
