# Generated by Django 5.0.6 on 2024-08-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0021_remove_experience_faq_experiencefaq_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=150, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='experiencefaq',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='experiencefaq',
            name='question',
        ),
        migrations.AddField(
            model_name='experience',
            name='faqs',
            field=models.ManyToManyField(blank=True, related_name='experiences', through='programs.ExperienceFaq', to='programs.faq'),
        ),
        migrations.AddField(
            model_name='experiencefaq',
            name='faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.faq'),
        ),
    ]
