# Generated by Django 5.0.6 on 2024-08-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0022_faq_remove_experiencefaq_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='course',
        ),
    ]
