# Generated by Django 5.0.6 on 2024-08-18 17:54

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0023_remove_experience_course'),
        ('providers', '0065_rename_price_courseprice_week_price_promotional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='course',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='school', chained_model_field='school', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.course'),
        ),
    ]
