# Generated by Django 5.0.6 on 2024-08-30 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_transaction_currency_and_more'),
        ('invoices', '0015_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invoices.invoice'),
        ),
    ]
