# Generated by Django 5.0.6 on 2024-08-19 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0007_agencybranch_apartment_number_and_more'),
        ('enquiries', '0031_contact_branch_contact_employee'),
        ('providers', '0065_rename_price_courseprice_week_price_promotional_and_more'),
        ('students', '0004_studentprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True)),
                ('enrollment_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('course_weekly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.schoolaccommodation')),
                ('accommodation_qty_weeks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.accommodationprice')),
                ('airport_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.schoolairporttransfer')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.agencybranch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.course')),
                ('course_qty_weeks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.courseprice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.employeeprofile')),
                ('enquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='enquiries.enquiry')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
        ),
    ]
