# Generated by Django 5.0.6 on 2024-08-18 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0031_contact_branch_contact_employee'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='enquiry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='enquiries.enquiry'),
        ),
    ]
