# Generated by Django 5.0.6 on 2024-08-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotation_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='phone',
        ),
    ]
