# Generated by Django 5.0.6 on 2024-08-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_remove_quotation_dob_remove_quotation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_enrolled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
