# Generated by Django 5.0.6 on 2024-08-27 07:59

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0065_rename_price_courseprice_week_price_promotional_and_more'),
        ('quotations', '0003_alter_quotation_course_qty_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='course_price_list',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='course', chained_model_field='course', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.coursepricelist'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='course_qty_weeks',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='course_price_list', chained_model_field='course_price_list', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.courseprice'),
        ),
    ]
