# Generated by Django 5.0.6 on 2024-08-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_quotation_is_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='is_enrolled',
            field=models.BooleanField(blank=True, default='no', null=True),
        ),
    ]
