# Generated by Django 5.0.6 on 2024-08-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_alter_quotation_is_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
