# Generated by Django 5.0.6 on 2024-08-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0065_rename_price_courseprice_week_price_promotional_and_more'),
        ('quotations', '0007_alter_quotation_airport_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='airport_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.schoolairporttransfer'),
        ),
    ]
