# Generated by Django 5.0.6 on 2024-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0027_alter_quotation_accommodation_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='accommodation_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='school_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
