# Generated by Django 5.0.6 on 2024-08-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0028_quotation_accommodation_total_quotation_school_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='is_enrolled',
            new_name='is_accepted',
        ),
    ]
