# Generated by Django 5.0.6 on 2024-08-27 17:55

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0031_contact_branch_contact_employee'),
        ('quotations', '0029_rename_is_enrolled_quotation_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='enquiry',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='student', chained_model_field='student', null=True, on_delete=django.db.models.deletion.CASCADE, to='enquiries.enquiry'),
        ),
    ]
