# Generated by Django 5.0.6 on 2024-08-27 19:49

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('providers', '0065_rename_price_courseprice_week_price_promotional_and_more'),
        ('quotations', '0030_alter_quotation_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.city'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='school',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='city', chained_model_field='city', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.school'),
        ),
    ]
