# Generated by Django 5.0.6 on 2024-08-27 20:00

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0065_rename_price_courseprice_week_price_promotional_and_more'),
        ('quotations', '0031_quotation_city_alter_quotation_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='airport_transfer_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='school',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='city', chained_model_field='address__city', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.school'),
        ),
    ]
