# Generated by Django 5.0.6 on 2024-08-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0032_quotation_airport_transfer_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(blank=True, choices=[('sent', 'sent'), ('approved', 'approved'), ('rejected', 'rejected'), ('expired', 'expired')], max_length=10, null=True),
        ),
    ]
