# Generated by Django 5.0.6 on 2024-08-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0033_remove_quotation_is_accepted_quotation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='date_start',
            new_name='accommodation_date_start',
        ),
        migrations.AddField(
            model_name='quotation',
            name='course_date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
