# Generated by Django 5.0.6 on 2024-08-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0034_rename_date_start_quotation_accommodation_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('INACTIVE', 'Inactive'), ('REJECTED', 'Rejected')], max_length=255, null=True, verbose_name='status'),
        ),
    ]
