# Generated by Django 5.0.6 on 2024-08-29 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_invoice_student'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.city'),
        ),
    ]
