# Generated by Django 5.0.6 on 2024-08-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_alter_invoice_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
