# Generated by Django 5.0.6 on 2024-07-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='locations.city')),
                ('street', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='schools/facilities')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.language')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.IntegerField()),
                ('info_email', models.EmailField(max_length=255)),
                ('bookings_email', models.EmailField(max_length=255)),
                ('academics_email', models.EmailField(max_length=255)),
                ('website', models.CharField(max_length=254)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.address')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.facility')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.school')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='Facilities',
            field=models.ManyToManyField(through='providers.SchoolFacility', to='providers.facility'),
        ),
        migrations.CreateModel(
            name='SchoolImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='schools/')),
                ('description', models.CharField(max_length=255)),
                ('alt', models.CharField(max_length=255)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.school')),
            ],
        ),
    ]
