# Generated by Django 5.0.6 on 2024-07-05 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_accommodation_schoolaccommodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolaccommodation',
            name='name',
        ),
    ]
