# Generated by Django 5.0.6 on 2024-07-06 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0015_rename_avgages_avgage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='schools/classroom_equipment')),
            ],
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='schools/accommodation'),
        ),
        migrations.AlterField(
            model_name='acreditation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='schools/acreditations'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='schools/activities'),
        ),
        migrations.CreateModel(
            name='SchoolClassroomEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.classroomequipment')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.school')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='school_equipment',
            field=models.ManyToManyField(through='providers.SchoolClassroomEquipment', to='providers.classroomequipment'),
        ),
    ]
