# Generated by Django 5.0.6 on 2024-07-08 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0017_rename_nationality_mix_nationalitymix_school_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationalitymix',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='nationalitymix',
            old_name='school_id',
            new_name='school',
        ),
    ]
