# Generated by Django 5.0.6 on 2024-07-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0017_nationalitymix_schoolnationalitymix'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='NationalityMix',
            field=models.ManyToManyField(through='providers.SchoolNationalityMix', to='providers.nationalitymix'),
        ),
    ]
