# Generated by Django 5.0.6 on 2024-07-15 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('providers', '0019_alter_contactinformation_academics_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAgencyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.agencybranch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.school')),
            ],
        ),
    ]
