# Generated by Django 5.0.6 on 2024-07-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0020_schoolagencybranch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolaccommodation',
            name='name',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_accommodation',
            field=models.ManyToManyField(through='providers.SchoolAccommodation', to='providers.accommodation'),
        ),
    ]
