# Generated by Django 5.0.6 on 2024-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0055_alter_courseprice_weeks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprice',
            name='weeks',
            field=models.PositiveIntegerField(),
        ),
    ]
