# Generated by Django 5.0.6 on 2024-08-06 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_currency_code'),
        ('providers', '0065_alter_school_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency'),
        ),
    ]
